# Copyright 2024-2026 Yuhui. All rights reserved.
#
# Licensed under the GNU General Public License, Version 3.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.gnu.org/licenses/gpl-3.0.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""SingStat custom types for client methods' responses."""

# This allows _TabledataDataRowColumnColumnDict to refer to itself
from __future__ import annotations

from datetime import date
from typing import Any, NotRequired, TypeAlias, TypedDict

Url: TypeAlias = str
"""URL of link."""

# Common types

class _DataDict(TypedDict):
    """Type definition for various custom types"""

    generatedBy: str
    """Generated by"""
    dateGenerated: date
    """Date generated"""

class _RecordDict(TypedDict):
    """Type definition for various custom types"""

    theme: NotRequired[str]
    """Theme"""
    subject: NotRequired[str]
    """Subject"""
    topic: NotRequired[str]
    """Topic"""
    id: NotRequired[str]
    """ID"""
    title: NotRequired[str]
    """Title"""
    frequency: NotRequired[str]
    """Frequency"""
    footnote: NotRequired[str]
    """Footnote"""
    dataLastUpdated: NotRequired[date]
    """Data last updated"""

class _SingStatDict(TypedDict):
    """Type definition for various custom types"""

    DataCount: int
    """Data count"""
    StatusCode: int
    """Status code"""
    Message: str
    """Message"""

# Resource ID

class _ResourceIdDataRecordDict(_RecordDict):
    """Type definition for _ResourceIdDataDict"""

    tableType: str
    """Table type"""

class _ResourceIdDataDict(_DataDict):
    """Type definition for ResourceIdDict"""

    total: int
    """Total"""
    records: list[_ResourceIdDataRecordDict]
    """Records"""

class ResourceIdDict(_SingStatDict):
    """Type definition for resource_id()"""

    Data: _ResourceIdDataDict
    """Data"""

# Metadata

class _MetadataDataRecordsRowDict(TypedDict):
    """Type definition for _MetadataDataRecordsTimeseriesRowDict and \
        _MetadataDataRecordsCrossSectionalMultiDimensionalCubeRowDict
    """

    rowText: str
    """Row text"""
    uoM: str
    """Unit of measurement"""
    footnote: str
    """Footnote"""

class _MetadataDataRecordsTimeseriesRowDict(_MetadataDataRecordsRowDict):
    """Type definition for _MetadataDataRecordsDict"""

    seriesNo: str
    """Series number"""

class _MetadataDataRecordsCrossSectionalMultiDimensionalCubeRowDict(
    _MetadataDataRecordsRowDict
):
    """Type definition for _MetadataDataRecordsDict"""

    rowNo: str
    """Row number"""

class _MetadataDataRecordsCrossSectionalMultiDimensionalCubeColumnDict(
    TypedDict
):
    """Type definition for \
        _MetadataDataRecordsCrossSectionalMultiDimensionalCubeDict
    """

    columnNo: str
    """Column number"""
    columnText: str
    """Column text"""
    footnote: str
    """Footnote"""

class _MetadataDataRecordsDict(_RecordDict):
    """Type definition for _MetadataDataRecordsTimeseriesDict and \
        _MetadataDataRecordsCrossSectionalMultiDimensionalCubeDict

    All fields are required. But they are typed as `NotRequired` because
    when the endpoint returns empty data, then this dict has no keys at all.
    """

    dataSource: NotRequired[str]
    """Data source"""

class _MetadataDataRecordsTimeseriesDict(_MetadataDataRecordsDict):
    """Type definition for _MetadataDataDict

    All fields are required. But they are typed as `NotRequired` because
    when the endpoint returns empty data, then this dict has no keys at all.
    """

    startPeriod: NotRequired[str]
    """Start period"""
    endPeriod: NotRequired[str]
    """End period"""
    total: NotRequired[int]
    """Total"""
    row: NotRequired[list[_MetadataDataRecordsTimeseriesRowDict]]
    """Row"""

class _MetadataDataRecordsCrossSectionalMultiDimensionalCubeDict(
    _MetadataDataRecordsDict
):
    """Type definition for _MetadataDataDict

    All fields are required. But they are typed as `NotRequired` because
    when the endpoint returns empty data, then this dict has no keys at all.
    """

    tableType: NotRequired[str]
    """Table type"""
    column1: NotRequired[
        list[_MetadataDataRecordsCrossSectionalMultiDimensionalCubeColumnDict]
    ]
    """Column 1"""
    column2: NotRequired[
        list[_MetadataDataRecordsCrossSectionalMultiDimensionalCubeColumnDict]
    ]
    """Column 2"""
    column3: NotRequired[
        list[_MetadataDataRecordsCrossSectionalMultiDimensionalCubeColumnDict]
    ]
    """Column 3"""
    column4: NotRequired[
        list[_MetadataDataRecordsCrossSectionalMultiDimensionalCubeColumnDict]
    ]
    """Column 4"""
    column5: NotRequired[
        list[_MetadataDataRecordsCrossSectionalMultiDimensionalCubeColumnDict]
    ]
    """Column 5"""
    column6: NotRequired[
        list[_MetadataDataRecordsCrossSectionalMultiDimensionalCubeColumnDict]
    ]
    """Column 6"""
    column7: NotRequired[
        list[_MetadataDataRecordsCrossSectionalMultiDimensionalCubeColumnDict]
    ]
    """Column 7"""
    column8: NotRequired[
        list[_MetadataDataRecordsCrossSectionalMultiDimensionalCubeColumnDict]
    ]
    """Column 8"""
    column9: NotRequired[
        list[_MetadataDataRecordsCrossSectionalMultiDimensionalCubeColumnDict]
    ]
    """Column 9"""
    column10: NotRequired[
        list[_MetadataDataRecordsCrossSectionalMultiDimensionalCubeColumnDict]
    ]
    """Column 10"""
    row: NotRequired[
        list[_MetadataDataRecordsCrossSectionalMultiDimensionalCubeRowDict]
    ]
    """Row"""

class _MetadataDataDict(_DataDict):
    """Type definition for MetadataDict"""

    records: _MetadataDataRecordsTimeseriesDict \
        | _MetadataDataRecordsCrossSectionalMultiDimensionalCubeDict
    """Records"""

class MetadataDict(_SingStatDict):
    """Type definition for metadata()"""

    Data: _MetadataDataDict
    """Data"""

# Tabledata

class _TabledataDataRowColumnDict(TypedDict):
    """Type definition for _TabledataDataRowColumnColumnDict, \
        _TabledataDataTimeseriesRowDict, and \
        _TabledataDataCrossSectionalMultiDimensionalCubeRowDict
    """

    key: str
    """Key"""
    value: NotRequired[Any]
    """Value"""

class _TabledataDataRowColumnColumnDict(TypedDict):
    """Type definition for \
        _TabledataDataCrossSectionalMultiDimensionalCubeRowDict
    """

    key: str
    """Key"""
    columns: list[
        _TabledataDataRowColumnColumnDict \
        | _TabledataDataRowColumnDict
    ]
    """Columns"""

class _TabledataDataRowDict(TypedDict):
    """Type definition for _TabledataDataTimeseriesRowDict and \
        _TabledataDataCrossSectionalMultiDimensionalCubeRowDict
    """

    rowText: str
    """Row text"""
    uoM: str
    """Unit of measurement"""
    footnote: str
    """Footnote"""

class _TabledataDataTimeseriesRowDict(_TabledataDataRowDict):
    """Type definition for _TabledataDataTimeseriesDict"""

    seriesNo: str
    """Series number"""
    columns: list[_TabledataDataRowColumnDict]
    """Columns"""

class _TabledataDataCrossSectionalMultiDimensionalCubeRowDict(
    _TabledataDataRowDict
):
    """Type definition for \
        _TabledataDataCrossSectionalMultiDimensionalCubeDict
    """

    rowNo: str
    """Row number"""
    columns: list[
        _TabledataDataRowColumnDict \
        | _TabledataDataRowColumnColumnDict
    ]
    """Columns"""

class _TabledataDataDict(_DataDict, _RecordDict):
    """Type definition for _TabledataDataTimeseriesDict and \
        _TabledataDataCrossSectionalMultiDimensionalCubeDict

    All fields are required. But they are typed as `NotRequired` because
    when the endpoint returns empty data, then this dict has no keys at all.
    """

    offset: NotRequired[int | None]
    """Offset"""
    limit: NotRequired[int]
    """Limit"""
    between: NotRequired[tuple[int, ...] | None]
    """Between"""
    search: NotRequired[str | None]
    """Search"""

class _TabledataDataTimeseriesDict(_TabledataDataDict):
    """Type definition for _TabledataDict

    All fields are required. But they are typed as `NotRequired` because
    when the endpoint returns empty data, then this dict has no keys at all.
    """

    datasource: NotRequired[str]
    """Data source"""
    sortBy: NotRequired[str | None]
    """Sort by"""
    timeFilter: NotRequired[str | None]
    """Time filter"""
    row: NotRequired[list[_TabledataDataTimeseriesRowDict]]
    """Row"""

class _TabledataDataCrossSectionalMultiDimensionalCubeDict(_TabledataDataDict):
    """Type definition for TabledataDict

    All fields are required. But they are typed as `NotRequired` because
    when the endpoint returns empty data, then this dict has no keys at all.
    """

    tableType: NotRequired[str]
    """Table type"""
    dataSource: NotRequired[str]
    """Data source"""
    row: NotRequired[
        list[_TabledataDataCrossSectionalMultiDimensionalCubeRowDict]
    ]
    """Row"""

class TabledataDict(_SingStatDict):
    """Type definition for tabledata()"""

    Data: _TabledataDataTimeseriesDict \
        | _TabledataDataCrossSectionalMultiDimensionalCubeDict
    """Data"""

__all__ = [
    'Url',

    'MetadataDict',
    'ResourceIdDict',
    'TabledataDict',
]
